apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    url: postgres:5432
    user: $__env{POSTGRES_USER}
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: $__env{POSTGRES_DB}
      sslmode: "disable"
    isDefault: true
